#!/usr/bin/env python
import rospy
import socket
import nmea_msgs.msg

rospy.init_node("gps_socket", anonymous=True)
topic_name = rospy.get_param("~topic", "/nmea_sentence")
pub = rospy.Publisher(topic_name, nmea_msgs.msg.Sentence, queue_size=10)
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
host = "192.168.43.236"
port = 50000

buf = []

if(rospy.has_param("~host")):
	host = rospy.get_param("~host")
if(rospy.has_param("~port")):
	port = int(rospy.get_param("~port"))
sock.connect((host, port))
try:
	while True:
		data = sock.recv(1024).split("\r\n")
		msg = nmea_msgs.msg.Sentence()
		msg.header.stamp = rospy.Time.now()
		for i in data:
			if(len(i)!=0):
				msg.sentence = i
				msg.header.frame_id = "garmin"
				pub.publish(msg)
except:
	sock.close()